### ISSUE TITLE
react 中文版的网站有问题

### ISSUE THREAD

**Issue by miniMonkey** [xiongwilee/frontend-resource#1]
https://www.reactjscn.com/
可以用这个替换

**Comment by shinrabansyou** [comment]
蛤？

发送自 Windows 10 版邮件应用

发件人: challenge
发送时间: 2018年5月18日 0:07
收件人: xiongwilee/frontend-resource
抄送: Subscribed
主题: [xiongwilee/frontend-resource] react 中文版的网站有问题 (#1)

https://www.reactjscn.com/
可以用这个替换

**Comment by miniMonkey** [comment]
http://www.bootcss.com/
这里面有很多框架官方文档的中文版翻译..刚才说的react的中文版.就是从这里找的.
你写在readme的那个网站已经成钓鱼网站了。

**Comment by xiongwilee** [comment]
fixed , thx
